### ISSUE TITLE
java.time compilation errors

### ISSUE THREAD

**Issue by logological** [dkpro/dkpro-jwpl#138]
Since July, Jenkins builds have been failing with the following error message.  I suspect this is due to a Java 1.7/1.8 mismatch in the build configuration.

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/svc_jenkins/workspace/JWPL - Java Wikipedia Library (GitHub)/de.tudarmstadt.ukp.wikipedia.api/src/main/java/de/tudarmstadt/ukp/wikipedia/api/Page.java:[179,77] cannot access java.time.OffsetDateTime
  class file for java.time.OffsetDateTime not found
[ERROR] /home/svc_jenkins/workspace/JWPL - Java Wikipedia Library (GitHub)/de.tudarmstadt.ukp.wikipedia.api/src/main/java/de/tudarmstadt/ukp/wikipedia/api/Page.java:[207,33] cannot access java.time.ZonedDateTime
  class file for java.time.ZonedDateTime not found
[ERROR] /home/svc_jenkins/workspace/JWPL - Java Wikipedia Library (GitHub)/de.tudarmstadt.ukp.wikipedia.api/src/main/java/de/tudarmstadt/ukp/wikipedia/api/Page.java:[298,33] cannot access java.time.LocalDateTime
  class file for java.time.LocalDateTime not found
[ERROR] /home/svc_jenkins/workspace/JWPL - Java Wikipedia Library (GitHub)/de.tudarmstadt.ukp.wikipedia.api/src/main/java/de/tudarmstadt/ukp/wikipedia/api/Page.java:[353,33] cannot access java.time.Instant
  class file for java.time.Instant not found
```

I'll try reconfiguring the Jenkins build to use Java 1.8 and see if that helps.

**Comment by logological** [comment]
Switching to Java 1.8 seems to have fixed the java.time errors, but now the compiler doesn't like the JavaDocs, because it validates them much more strictly than in Java 1.7.  I suspect the dependency on Java 1.8 was introduced by Commit 0c2604a3dffa130d82981e4c3845821eb7453dac or Commit 
3d5da478da450b179b7aeeec0404d0ba2d56f7f8 (which fixed Issue #137).  Was this intentional?  If so, then we either need to fix all the JavaDocs, or else [suppress the JavaDoc errors](https://stackoverflow.com/questions/22528767/how-to-work-around-the-stricter-java-8-javadoc-when-using-maven).  We might also need to update the documentation in case it claims JWPL works with Java 1.7.

**Comment by daxenberger** [comment]
The first problem here is that we didn't notice the broken build before (I guess the respective notification got stuck in the mailing list queue of the dev-list; @ferschke @zesch I think one of you manages this list - could you make sure that those mails will pass?).

The second problem (java 8 dependency or incompatibility of java.time) is has most probably been introduced by 0c2604a. I guess this is related to the updated hibernate version. JWPL has not yet fully migrated to Java 8 - although this might be doable with reasonable effort. 
@mawiesne were you able to compile JWPL after your changes with Java 7? If not, could you make your changes compatible with Java 7?

**Comment by logological** [comment]
Besides the JavaDoc issue, what else needs to be done to get JWPL working with Java 8?  In my local Eclipse installation, everything seems to compile without errors with Java 8 (though I did not run any unit tests).

**Comment by reckart** [comment]
I would suppose that the chances are good that no additional changes need to be made except fixing the JavaDoc (search for ": error:" in the Jenkins output, don't get distracted by warnings that just look like errors). If JWPL would have made invalid assumptions, e.g. about the order of items in HashSets or something like that, then that might require additional work if this order has changed from Java 7 to Java 8. But I just hope that such invalid assumptions were not made.

**Comment by daxenberger** [comment]
Agree with @reckart  
I don't know of other particular obstacles for upgrading to Java 8.

**Comment by reckart** [comment]
@daxenberger @logological Jenkins is successfully building JWPL with Java 8 nowadays. I think this issue can be closed now.

**Comment by daxenberger** [comment]
@reckart thanks
